#!/bin/bash

if [ $# -ne 2 ]; then
	echo "usage: `basename $0` <PR URL> <from-commit URL>"
	echo -e "\nexample: `basename $0` https://github.com/zephyrproject-rtos/zephyr/pull/116318 https://github.com/zephyrproject-rtos/zephyr/commit/301c36b47f1402a3bf5ee550c9e51d0cabbe920b"
	exit 1
fi

token_path=`dirname "$0"`/github_token
if ! [ -f "$token_path" ]; then
	echo "missing token ($token_path not found)"
	exit 1
fi

pr_num=$(cut -d / -f 7 <<< $1 | cut -d# -f1)
from_rev=$(cut -d / -f 7 <<< $2)
remote=$(git remote -v | grep -m 1 -F "$(cut -d / -f 1-5 <<< $1)" | cut -d $'\t' -f 1)
if [ "$remote" = "" ]; then
	echo "missing remote - Did you run this from the repository you are range-diffing?"
	exit 1
fi

repo=$(cut -d / -f 4-5 <<< $1)
token=$(cat "$token_path")
base=$(curl -s -H "Authorization: token $token" "https://api.github.com/repos/$repo/pulls/$pr_num" | jq -r '.base.ref')
if [ "$base" == 'null' ]; then
	echo "failed to retrieve .base.ref"
	exit 1
fi

branch_commit_count() {
	git rev-list --count $(git merge-base "$remote/$base" $1)..$1
}

git fetch "$remote" "$base" "${from_rev}:from_rev" "pull/${pr_num}/head:to_rev" || exit $?

from_count=$(branch_commit_count from_rev)
to_count=$(branch_commit_count to_rev)

git range-diff from_rev~${from_count}..from_rev to_rev~${to_count}..to_rev

git branch -D from_rev to_rev
